# Generated by Django 4.2.4 on 2023-09-13 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='icon')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is_enable')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_time')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modify_date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='image')),
                ('is_main', models.BooleanField(blank=True, default=False, help_text='Active To Publish MAIN Image', null=True, verbose_name='main')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='modify_date')),
            ],
            options={
                'verbose_name': 'ImageProduct',
                'verbose_name_plural': 'ImagesProduct',
                'db_table': 'imagesproduct',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='price')),
                ('discription', models.CharField(blank=True, max_length=400, null=True, verbose_name='discription')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is_enable')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('discount', models.IntegerField(default=0, verbose_name='discount')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='modify_date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=3.4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rate')),
            ],
        ),
    ]
