# Generated by Django 4.2.4 on 2023-09-13 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(blank=True, to='Product.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.imageproduct', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.rating'),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='category',
            name='parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.category', verbose_name='parrent'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_id',
            field=models.ManyToManyField(blank=True, to='Product.product', verbose_name='product'),
        ),
    ]
