# Generated by Django 4.2.4 on 2023-09-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_category_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_id',
        ),
    ]
