# Generated by Django 4.2.4 on 2023-09-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_remove_category_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='categories',
        ),
    ]
