# Generated by Django 4.2.4 on 2023-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_rename_category_id_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_by', to='Product.category', verbose_name='category'),
        ),
    ]
