# Generated by Django 4.2.4 on 2023-09-16 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate_id',
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=3.4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='rating',
            name='prodcut_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product'),
        ),
    ]
