# Generated by Django 4.2.4 on 2023-09-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_product_rate_id_product_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='prodcut_id',
            new_name='product_id',
        ),
    ]
