# Generated by Django 4.2.4 on 2023-09-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_rename_prodcut_id_rating_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rate_point', 'verbose_name_plural': 'rates_points'},
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
    ]
