# Generated by Django 4.2.4 on 2023-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_add_trigger'),
        ('Product', '0013_alter_rating_options_alter_rating_table'),
    ]

    operations = [
    ]
