# Generated by Django 4.2.4 on 2023-09-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_merge_20230916_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
