# Generated by Django 4.2.4 on 2023-09-14 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdevice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
